//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionAde.Utils.OutfitEngineService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OutfitEngineService.IOutfitEngineService")]
    public interface IOutfitEngineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutfitEngineService/HasValidCombinations", ReplyAction="http://tempuri.org/IOutfitEngineService/HasValidCombinationsResponse")]
        bool HasValidCombinations(System.Collections.Generic.List<int> garments, System.Collections.Generic.List<int> flavors);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOutfitEngineService/CreateOutfits")]
        void CreateOutfits(int closetId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOutfitEngineService/AddOutfits")]
        void AddOutfits(int closetId, System.Collections.Generic.List<int> addedGarments);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOutfitEngineServiceChannel : FashionAde.Utils.OutfitEngineService.IOutfitEngineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OutfitEngineServiceClient : System.ServiceModel.ClientBase<FashionAde.Utils.OutfitEngineService.IOutfitEngineService>, FashionAde.Utils.OutfitEngineService.IOutfitEngineService {
        
        public OutfitEngineServiceClient() {
        }
        
        public OutfitEngineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutfitEngineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutfitEngineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutfitEngineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool HasValidCombinations(System.Collections.Generic.List<int> garments, System.Collections.Generic.List<int> flavors) {
            return base.Channel.HasValidCombinations(garments, flavors);
        }
        
        public void CreateOutfits(int closetId) {
            base.Channel.CreateOutfits(closetId);
        }
        
        public void AddOutfits(int closetId, System.Collections.Generic.List<int> addedGarments) {
            base.Channel.AddOutfits(closetId, addedGarments);
        }
    }
}
