
 ALTER TABLE fashionade_dev.registereduser
 DROP FOREIGN KEY FK34E1D74B396708F6,
 DROP FOREIGN KEY FK34E1D74B3BBCEB6C,
 ADD NewMail VARCHAR(120) AFTER RegistrationCode;
ALTER TABLE fashionade_dev.registereduser
 ADD CONSTRAINT FK34E1D74B396708F6 FOREIGN KEY (BasicUserId) REFERENCES fashionade_dev.basicusers (BasicUserId) ON UPDATE RESTRICT ON DELETE RESTRICT,
 ADD CONSTRAINT FK34E1D74B3BBCEB6C FOREIGN KEY (SizeId) REFERENCES fashionade_dev.usersizes (UserSizeId) ON UPDATE RESTRICT ON DELETE RESTRICT;
