//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionAde.OutfitUpdaterExecutor.OutfitUpdaterReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OutfitUpdaterReference.IOutfitUpdaterService")]
    public interface IOutfitUpdaterService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOutfitUpdaterService/UpdateFeeds")]
        void UpdateFeeds();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOutfitUpdaterService/MatchOutfitUpdaters")]
        void MatchOutfitUpdaters();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOutfitUpdaterServiceChannel : FashionAde.OutfitUpdaterExecutor.OutfitUpdaterReference.IOutfitUpdaterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OutfitUpdaterServiceClient : System.ServiceModel.ClientBase<FashionAde.OutfitUpdaterExecutor.OutfitUpdaterReference.IOutfitUpdaterService>, FashionAde.OutfitUpdaterExecutor.OutfitUpdaterReference.IOutfitUpdaterService {
        
        public OutfitUpdaterServiceClient() {
        }
        
        public OutfitUpdaterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutfitUpdaterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutfitUpdaterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutfitUpdaterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateFeeds() {
            base.Channel.UpdateFeeds();
        }
        
        public void MatchOutfitUpdaters() {
            base.Channel.MatchOutfitUpdaters();
        }
    }
}
