//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FashionAde.TestsUsingDevDatabase.OutfitUpdaters {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OutfitUpdaters.IOutfitUpdaterService")]
    public interface IOutfitUpdaterService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOutfitUpdaterService/UpdateFeeds")]
        void UpdateFeeds();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IOutfitUpdaterService/MatchOutfitUpdatersForCloset")]
        void MatchOutfitUpdatersForCloset(int closetId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IOutfitUpdaterServiceChannel : FashionAde.TestsUsingDevDatabase.OutfitUpdaters.IOutfitUpdaterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OutfitUpdaterServiceClient : System.ServiceModel.ClientBase<FashionAde.TestsUsingDevDatabase.OutfitUpdaters.IOutfitUpdaterService>, FashionAde.TestsUsingDevDatabase.OutfitUpdaters.IOutfitUpdaterService {
        
        public OutfitUpdaterServiceClient() {
        }
        
        public OutfitUpdaterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutfitUpdaterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutfitUpdaterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutfitUpdaterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateFeeds() {
            base.Channel.UpdateFeeds();
        }
        
        public void MatchOutfitUpdatersForCloset(int closetId) {
            base.Channel.MatchOutfitUpdatersForCloset(closetId);
        }
    }
}
