using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.9.3.4")]
[assembly: AssemblyFileVersionAttribute("0.9.3.4")]
[assembly: AssemblyInformationalVersionAttribute("0.9.3.4")]
[assembly: AssemblyCopyrightAttribute("Copyright © Abundant Closet LLC 2010")]
[assembly: AssemblyCompanyAttribute("Abundant Closet LLC")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]

